In [ ]:
import numpy as np
import pandas as pd

In [ ]:
s1 = np.random.rand(4)
s2 = np.random.rand(4)
s3 = np.random.rand(4)
s4 = np.random.rand(4)

In [ ]:
s1

array([0.43782504, 0.15290392, 0.51155791, 0.23187187])

In [ ]:
s2

array([0.89496463, 0.00953099, 0.37244632, 0.79540465])

In [ ]:
s3

array([0.33610909, 0.05593567, 0.37587487, 0.56760307])

In [ ]:
s4

array([0.79334508, 0.11927958, 0.06848108, 0.64744336])

In [ ]:
df = pd.DataFrame([s1,s2,s3,s4])

In [ ]:
df

          0         1         2         3
0  0.437825  0.152904  0.511558  0.231872
1  0.894965  0.009531  0.372446  0.795405
2  0.336109  0.055936  0.375875  0.567603
3  0.793345  0.119280  0.068481  0.647443

In [ ]:
df = df.T

In [ ]:
df

          0         1         2         3
0  0.437825  0.894965  0.336109  0.793345
1  0.152904  0.009531  0.055936  0.119280
2  0.511558  0.372446  0.375875  0.068481
3  0.231872  0.795405  0.567603  0.647443

In [ ]:
df = df.T

In [ ]:
df

          0         1         2         3
0  0.437825  0.152904  0.511558  0.231872
1  0.894965  0.009531  0.372446  0.795405
2  0.336109  0.055936  0.375875  0.567603
3  0.793345  0.119280  0.068481  0.647443

In [ ]:
df.columns = (['Random Value 1', 'Random Value 2', 'Random Value 3', 'Random Value 4'])

In [ ]:
df

   Random Value 1  Random Value 2  Random Value 3  Random Value 4
0        0.437825        0.152904        0.511558        0.231872
1        0.894965        0.009531        0.372446        0.795405
2        0.336109        0.055936        0.375875        0.567603
3        0.793345        0.119280        0.068481        0.647443

In [ ]:
df.describe()

       Random Value 1  Random Value 2  Random Value 3  Random Value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.615561        0.084413        0.332090        0.560581
std          0.270405        0.064096        0.187300        0.238597
min          0.336109        0.009531        0.068481        0.231872
25%          0.412396        0.044335        0.296455        0.483670
50%          0.615585        0.087608        0.374161        0.607523
75%          0.818750        0.127686        0.409796        0.684434
max          0.894965        0.152904        0.511558        0.795405

In [ ]:
df.isnull()

   Random Value 1  Random Value 2  Random Value 3  Random Value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False

In [ ]:
for i in df.columns:
  print(i, df[i].dtype)

Random Value 1 float64
Random Value 2 float64
Random Value 3 float64
Random Value 4 float64

In [ ]:
df.loc[0:, 'Random Value 2':'Random Value 3']

   Random Value 2  Random Value 3
0        0.152904        0.511558
1        0.009531        0.372446
2        0.055936        0.375875
3        0.119280        0.068481

In [ ]:
df.iloc[0:, 1:3]

   Random Value 2  Random Value 3
0        0.152904        0.511558
1        0.009531        0.372446
2        0.055936        0.375875
3        0.119280        0.068481